export const testimonial = {
  testimonialContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    height: "100%",
    width: "100%",
    boxSizing: "border-box",
    padding: { xs: "20px 20px", md: "20px 80px", xl: "20px 130px" },
  },
  testimonialHeadingContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
  },
  heading: {
    color: "#32373C",
    fontSize: "20px",
    fontWeight: "900",
    textAlign: "left",
  },
  testimonialBoxContainer: {
    display: "flex",
    justifyContent: { xs: "center", md: "space-between" },
    alignItems: "center",
    flexWrap: "wrap",
    width: "100%",
    height: "100%",
    padding: "20px 0px",
  },
  testimonialBox: {
    display: "flex",
    flexDirection: { xs: "column-reverse", lg: "row" },
    justifyContent: "space-between",
    alignItems: "center",
    width: { xs: "100%", md: "48%", xl: "49%" },
    height: "100%",
    padding: "20px",
    boxShadow: "0px 0px 10px #00000029",
    borderRadius: "10px",
    marginBottom: "20px",
    gap: { xs: 2, lg: 0 },
  },
  testimonialHeading: {
    width: { xs: "90%", lg: "80%" },
    color: "#32373C",
    fontSize: "13px",
    fontWeight: 300,
    fontFamily: "Poppins",
  },
  testimonialNameContainer: {
    display: "flex",
    flexDirection: { xs: "column-reverse", lg: "column" },
    justifyContent: { xs: "space-between", lg: "center" },
    alignItems: { xs: "flex-start", lg: "center" },
    width: { xs: "90%", lg: "20%" },
  },
  testimonialName: {
    color: "#32373C",
    fontFamily: "Poppins",
    fontSize: { sm: 18, xs: 16 },
    fontWeight: "600",
    lineHeight: "24px",
    textAlign: "center",
  },
  image: { width: { sm: 100, xs: 90 } },
};
