export const about = {
  aboutContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    height: "100%",
    width: "100%",
    boxSizing: "border-box",
    padding: { xs: "20px 15px", md: "20px 80px" },
    fontFamily: "Poppins",
  },
  aboutFirstContainer: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    justifyContent: "space-between",
    alignItems: "flex-start",
    width: "100%",
    height: "100%",
    mb: 2,
  },
  firstColumn: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: { xs: "100%", md: "47%" },
    height: "100%",
    margin: { xs: "10px 0", md: 0 },
  },
  heading: {
    color: "#32373C",
    fontSize: "20px",
    fontWeight: 600,
    textAlign: "left",
    marginBottom: { xs: "20px", md: "40px" },
    fontFamily: "Poppins",
  },
  subHeading: {
    fontFamily: "Poppins",
    fontSize: { xs: "12px", sm: "14px", md: "16px", lg: "17px" },
    fontWeight: 400,
    lineHeight: 1.8,
    textAlign: "left",
    margin: "0 0 20px 0",
  },
  description: {
    fontFamily: "Poppins",
    fontSize: { xs: "12px", sm: "14px", md: "16px", lg: "18px" },
    fontWeight: 450,
    textAlign: "left",
    margin: "0 0 20px 0",
  },
  secondColumn: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: { xs: "center", md: "flex-end" },
    width: { xs: "100%", md: "47%" },
    height: "100%",
    margin: { xs: "10px 0", md: 0 },
  },
  bannerImg: {
    width: { xs: "100%", md: "390px", lg: "550px", xl: "800px" },
    height: { xs: "100%", md: "250px", lg: "300px", xl: "382px" },
  },
  imageRowContainer: {
    display: "flex",
    gap: 2,
    flexDirection: { xs: "column", md: "row" },
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    height: "100%",
    mb: 2,
  },
};
