export const styles = {
  bgCon: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    position: "relative",
    mb: { xs: "40%", sm: "20%" },
    cursor: "pointer",
  },

  testContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    bgcolor: "rgba(226, 226, 226, 1)",
    height: "25vh",
    zIndex: "-2",
  },

  head: {
    fontSize: "28px",
    lineHeight: "33px",
    color: "rgba(50, 55, 60, 1)",
    mt: "1%",
    mb: "10%",
    fontfamily: "Montserrat",
    fontWeight: 700,
  },

  cardContainer: {
    display: "flex",
    justifyContent: "flex-end",
    position: "absolute",
    top: 150,
    alignItems: "center",
    width: { xs: "80%", sm: "60%", lg: "60%" },
    bgcolor: "#ffffff",
    borderRadius: "2px",
    border: "1px solid #cccccc",
  },
  cardContentCon: {
    display: "flex",
    padding: "0%",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-end",
    width: { xs: "50%", sm: "60%" },
    position: "relative",
  },
  text1: {
    fontSize: { xs: "0.5rem", sm: "0.7rem", lg: "18px" },
    fontWeight: "400",
    color: "#878787",
  },
  personImageCon: {
    width: { xs: "80px", lg: "150px" },
    height: { xs: "80px", lg: "150px" },
  },
  personImg: {
    width: "100%",
  },
  personName: {
    mt: "10px",
    mb: "10px",
  },

  personCardContainer: {
    display: "flex",
    padding: "4%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    bgcolor: "#ffffff",
  },
  borderImg1: {
    width: { xs: "25%", lg: "15%" },
    height: { xs: "110%", lg: "169%" },
    position: "absolute",
    top: { xs: "130px", lg: "121px" },

    left: { xs: "17vw", sm: "22vw", lg: "24vw" },
    zIndex: "3",
  },
  borderImg2: {
    width: { xs: "30%", sm: "15%", lg: "15%" },
    position: "absolute",
    top: { xs: "129px", lg: "120px" },
    height: { xs: "97%", lg: "149%" },
    right: { xs: "12vw", sm: "22vw", lg: "23vw" },
    zIndex: "-1",
  },

  quoteImg1: {
    width: { xs: "25px", sm: "40px", md: "50px" },
    height: { xs: "20px", sm: "35px", md: "40px" },
    zIndex: "3",
    position: "absolute",
    top: { xs: "137px", sm: "129px", lg: "122px" },
    left: { xs: "27vw", sm: "29vw", lg: "33vw" },
  },
  quoteImg2: {
    width: { xs: "25px", sm: "40px", md: "50px" },
    height: { xs: "20px", sm: "35px", md: "40px" },
    zIndex: "3",
    position: "absolute",
    bottom: { xs: "-105px", sm: "-126px", md: "-145", lg: "-218px" },
    right: { xs: "18vw", sm: "27vw", lg: "33vw" },
  },
  forWordIcon: {
    position: "absolute",
    left: { xs: "1%", sm: "12%", md: "12%" },
    top: { xs: 196, lg: 187, xl: 200 },

    fontSize: "20px",
    bgcolor: "#ffffff",
    zIndex: "10",
    padding: "1%",
    color: "#232323",
    borderRadius: "50%",
    border: "1px solid rgba(226, 226, 226, 1)",
    boxShadow: "1px 2px 2px 1px #cccccc",
  },
  backWardIcon: {
    position: "absolute",
    top: { xs: 196, lg: 193, xl: 200 },
    right: { xs: "1%", sm: "12%", md: "12%" },
    fontSize: "20px",
    bgcolor: "#ffffff",
    zIndex: "10",
    padding: "1%",
    color: "#232323",
    borderRadius: "50%",
    border: "1px solid rgba(226, 226, 226, 1)",
    boxShadow: "1px 2px 2px 1px #cccccc",
  },
};
